chrome_browser:
  hostname: chrome-browser
  #ubuntu image
  image: selenium/standalone-chrome:latest
  #raspberry pi image
  #image: seleniarm/standalone-chromium:latest
  ports:
    - 4444:4444
  restart: unless-stopped
  shm_size: 512mb
  depends_on:
    - changedetectionio
