changedetectionio:
  image: ghcr.io/dgtlmoon/changedetection.io
  container_name: changedetection
  hostname: changedetection
  volumes:
    - ./volumes/changedetection-data:/datastore
  environment:
    #only enable webdriver if chrome_browser container is also installed
    - WEBDRIVER_URL=http://chrome-browser:4444/wd/hub
  ports:
    - 5000:5000
  restart: unless-stopped
